Add ruby version requirement '>= 2.0.0'
With ruby 1.9.3 #serialized_json raises an exception:
```
NameError:
       undefined local variable or method `caller_locations' for FastJsonapi::MultiToJson:Module
```
`Kernel#caller_locations` was added in ruby '2.0.0'
Source: https://docs.ruby-lang.org/en/2.2.0/NEWS-2_0_0.html